---
name: deploy to gh pages

on:
  push:
    branches:
      - main
    paths:
      - pages/**

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    uses: techtales-io/github-workflows/.github/workflows/deploy-gh-pages.yaml@acc20b59e4f68b7c4a199ec0054f533d20beea8f # v0.2.0
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      runner: ubuntu-latest
      environment: github-pages
      path: pages
